import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
// import configPromise from "@payload-config";
// import { getPayload } from "payload";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import "../globals.css";
import Navbar from "@/app/(frontend)/Navbar";
import Footer from "@/app/(frontend)/Footer";
import SearchFilters from "@/app/(frontend)/search-filters";
import {TRPCReactProvider} from "@/trpc/client";
import {getQueryClient, trpc} from "@/trpc/server";
import {Suspense} from "react";
import {Toaster} from "@/components/ui/sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

// const payload = await getPayload({
//   config: configPromise,
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const cateData = await payload.find({
//   collection: "categories",
//   depth: 1,
//   pagination: false,
//   sort: "alt",
//   select: {
//     alt: true,
//     slug: true,
//     color: true,
//     parent: true,
//     subcategories: true,
//   },
//   where: {
//     parent: {
//       exists: false
//     },
//   },
// });


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  void queryClient.prefetchQuery(trpc.categories.getMany.queryOptions());

  return (
    <html
      lang="en"
      className={`${dmSans.className} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <TRPCReactProvider>
          <Navbar />
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Suspense fallback={<p>Loading...</p>}>
              <SearchFilters />
            </Suspense>
            <main className="flex-1 bg-[#F4F4F0]">{children}
            <Toaster />
            </main>
          </HydrationBoundary>
        </TRPCReactProvider>
        <Footer />
      </body>
    </html>
  );
}
