import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import configPromise from "@payload-config";
import { getPayload } from "payload";
import "../globals.css";
import Navbar from "@/app/(frontend)/Navbar";
import Footer from "@/app/(frontend)/Footer";
import SearchFilters from "@/app/(frontend)/search-filters";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

const payload = await getPayload({
  config: configPromise,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cateData = await payload.find({
  collection: "categories",
  depth: 1,
  pagination: false,
  sort: "alt",
  select: {
    alt: true,
    slug: true,
    color: true,
    parent: true,
    subcategories: true,
  },
  where: {
    parent: {
      exists: false
    },
  },
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.className} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Navbar />
        {/*From where does the data come from*/}
        <SearchFilters categories={cateData.docs} />
        <main className="flex-1 bg-[#F4F4F0]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
